export const REQUEST_ClIENTS = 'REQUEST_ClIENTS'
export const FETCH_ClIENTS = 'FETCH_ClIENTS'
export const SET_CURRENT_ClIENT = 'SET_CURRENT_ClIENT'
export const REQUEST_DECLARANTS = 'REQUEST_DECLARANTS'
export const FETCH_DECLARANTS = 'FETCH_DECLARANTS'
export const UPDATE_NEW_DECLARANTS_ARRAY = 'UPDATE_NEW_DECLARANTS_ARRAY'
export const PUSH_NEW_DECLARANT = 'PUSH_NEW_DECLARANT'
export const UPDATE_CURRENT_NEW_DECLARANT = 'UPDATE_CURRENT_NEW_DECLARANT'

